# Copyright 2020 MaaT Pharma
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

##############
# This script normalizes a large count table by gene length (with low RAM usage). 
# Before running it, the lines of the count table must be split into several files. It must then be launched sequentially on all the files.
# For instance (bash):
# split -l 20583 --numeric-suffixes counts.tsv counts_split_
# nb_samples=1145
# for i in `ls counts_split_*`; do Rscript norm_by_gene_length.R $i $nb_samples; done
#
# The "counts.tsv" file must contain the following tab-separated columns: geneID <SAMPLE_ID_1> <SAMPLE_ID_2> ... <SAMPLE_ID_nb_samples>. All columns must contain numeric values.
#
# The "gene_length.tsv" file must be composed of two tab-separated columns (numeric values): geneID length. For IGC, this table can be generated by extracting the first and third columns from the file "IGC.annotation_OF.summary.gz". 
##############

library(data.table)
library(dplyr)

args <- commandArgs(trailingOnly=TRUE)

if (length(args)!=2) {
  stop("Two argument must be supplied (input file and number of samples)", call.=FALSE)
}

output_file <- "counts_norm.tsv"
nb_samples <- as.numeric(args[2])

##############
# Importing length information for each gene 
#

catalog_annot <- fread("gene_length.tsv", sep="\t")
rownames(catalog_annot) <- as.character(unlist(catalog_annot[,1]))
catalog_annot <- catalog_annot[,c(1,2)]
colnames(catalog_annot) <- c("geneID","length")
catalog_annot <- as.data.frame(catalog_annot)

# 
##############

##############
# Normalizing each line of the count table by the length of the corresponding gene
#

col_length <- nb_samples + 2
col_samples <- nb_samples + 1

ab_profile <- fread(args[1])
ab_profile <- as.data.frame(sapply(ab_profile, as.numeric))
rownames(ab_profile) <- ab_profile[,1]
colnames(ab_profile) <- c("geneID", colnames(ab_profile)[2:col_samples])

ab_profile <- inner_join(ab_profile, catalog_annot,by="geneID")

ab_profile_norm <- apply(ab_profile, 1, function(x) as.numeric(x[2:col_samples])/as.numeric(x[col_length]))
ab_profile_norm_t <- as.data.frame(t(ab_profile_norm))
rownames(ab_profile_norm_t) <- ab_profile[,1]
colnames(ab_profile_norm_t) <- colnames(ab_profile)[2:col_samples]

# 
##############

fwrite(ab_profile_norm_t, file=output_file, sep="\t",row.names=T,quote=F,append=T)
