# Copyright 2020 MaaT Pharma
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

##############
# Before running this script, the bin-specific .tsv files generated by MSPminer can be converted into a single file using the following bash command: 
# output_dir="MSPminer_output_folder"; for i in $output_dir/msp_*; do cat $i/modules.tsv | grep -v "gene_name" | awk -v msp_id="$(basename $i)" '{print(msp_id,"\t",$3)}' ; done > "$output_dir/output_$(basename $output_dir).tsv"  
##############

library(dplyr)

## Functions 
toCNL_singleton <- function(binningBBF, filename) {
  binningCNL <- left_join(binningBBF,genesRefCNL,by="@@SEQUENCEID")

  genesCNL <- c()
  for (binid in unique(binningCNL$BINID)) {
    genesCNL <- as.character(binningCNL[binningCNL$BINID==binid,"seq_id"])
    
    write.table(t(genesCNL), append=TRUE,file=filename, quote=FALSE, sep=" ",row.names = FALSE, col.names = FALSE)
  }
  unassigned_list <- setdiff(genesRefCNL[,"seq_id"],binningCNL[,"seq_id"])
  
  # add a line per unassigned sequence
  for (i in unassigned_list) {
    singletonCNL <- i
    
    write.table(singletonCNL, append=TRUE,file=filename, quote=FALSE, sep=" ",row.names = FALSE, col.names = FALSE)
  }
}

toBBF <- function(binningOutput, filename, samplename) {
  fileConn<-file(filename)
  writeLines(c("@Version:0.9.1",paste0("@SampleID:",samplename),""), fileConn)
  close(fileConn)
  write.table(binningOutput,file=filename,append = TRUE, quote=FALSE, sep="\t",row.names = FALSE)
}

## Required inputs 
# a dataframe composed of two columns : sequence_name | seq_id 
my_df <- data.frame(sequence_names=c("sequence_A","sequence_B")) # to modify 
genesRefCNL <- my_df %>% mutate(seq_id=group_indices(.,sequence_names))
colnames(genesRefCNL) <- c("@@SEQUENCEID", "seq_id")
# a vector of csv, txt or tsv file paths, each file must be composed of two columns : sequence_name | bin_id
binning_output_to_convert <- # c("../path/to/file") 

for (file in binning_output_to_convert) {
  print(file)
  if (file_ext(file)=="csv") { 
    output_binner <- read.csv(file,header=FALSE,strip.white = T)
    colnames(output_binner) <- c("@@SEQUENCEID", "BINID")
    output_binner$BINID <- paste0("bin_",output_binner$BINID) # if bin id corresponds to a number
  }
  else  {  #.tsv, .txt 
    output_binner <- read.delim(file,header=FALSE,strip.white = T)
    colnames(output_binner) <- c("@@SEQUENCEID", "BINID") 
  }
  
  toBBF(output_binner,paste0(str_replace(basename(file),paste0(".",file_ext(file)),""),".binning"),"SampleName")
  toCNL_singleton(output_binner,paste0(str_replace(basename(file),paste0(".",file_ext(file)),""),".cnl"))
}
